#
# 开发环境配置文件
#
#########################################

# 全局配置
logfile                 = 'config/log.json'     # 日志存放位置，若配置后无对应的path, 则也会输出至os.Stdout default: os.Stdout
http_server_port        = 5000
host                    = '0.0.0.0'

[redisCfg]
    redis_svr               = ["redis1"]
    redis_conn_timeout      = 1000                      # redis连接超时 毫秒
    redis_read_timeout      = 500                       # redis读超时 毫秒
    redis_write_timeout     = 500                       # redis写超时 毫秒
    redis_max_idle          = 200                       # 最大空闲连接
    redis_max_active        = 2000                      # 最大活动连接
    redis_expire_second     = 600                       # redis数据过期时间 秒 线上配置10分钟 60


[kafkaProducerCfg]
    brokerlist      = "kafka1"
    batchnum        = 3
    partitionnum    = 10
    producenum      = 1
    dialtimeout     = 1000
    writetimeout    = 5000
    readtimeout     = 5000
    returnerror     = true
    returnsuccess   = true
    flushfrequency  = 100
    channelbuffersize = 100000

[kafkaConsumerCfg]
    [kafkaConsumerCfg.CHATROOM]
        topic                   = 'CHATROOM' #订阅的topic, 必需
        group                   = ''                    #位于的gourp, default:'default'
        processTimeout          = 25000                 #任务可以处理的时间 default: '60s'
        commitInterval          = 5000                  #提交offset数据的间隔 default: '10s'
        retryTimes              = 3                     #任务失败后的重试次数 default: 5
        metaMaxRetry            = 3                     #获取meta信息失败后的重试次数 default:3
        channelSize             = 20                    #本地允许缓存的消息条数 default: 256
        httpTimeout             = 20000                 #处理任务时http调用的超时时间 default: 20s
        zookeeperTimeout        = 1000                  #连接zookeeper的超时时间 default: '1s'
        metaRefreshFrequency    = 60000                 #meta信息的刷新频率 default: '20min'
        zookeeperChroot         = ''                    #zookeeper chroot default: ''
        retryInterval           = 500                   #messgae handle 失败后
        zookeeperAddresses      = ["zookeeper1"]